version: '3.3'

services:
  web:
    image: registry.pg3.io:5000/pg3io/crawl:${VERSION:-latest}
    volumes:
      - /data/crawl/:/sources/
    environment:
      - "LIST=/sources/list.yml"
    # logging into logstash
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: crawl.status
