version: '3.3'

services:
  db:
    image: influxdb:2.0
    ports:
      - '8086:8086'
    volumes:
      - ./influxdbv2:/root/.influxdbv2
    networks:
      - app-to-db
      - db-to-grafana
    

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - './grafana:/var/lib/grafana'
    networks:
      - db-to-grafana
    depends_on:
      - db

  influxdb_cli:
    image: quay.io/influxdb/influxdb:v2.0.3
    entrypoint: influx setup --bucket crawl-url -t IyxHCtOAH68QF8qTVAY2Jge-u3CdcINp5nsIK0Eme0cb4GeYqtADvrS3SYQaOgkccMdACvQpHxvbPowMhzr53g== -o PG3 --username=pg3 --password=password --host=http://db:8086 -f
    restart: on-failure:10
    depends_on:
      - db
    networks:
      - app-to-db
  
  web:
    depends_on:
      - db
    restart: on-failure:10
    build: .
    volumes:
      - ./sources/:/sources
    environment:
      - "INFLUXDB-HOST=http://db:8086"
      - LIST=/sources/list.yml
      - INFLUXDB-TOKEN=IyxHCtOAH68QF8qTVAY2Jge-u3CdcINp5nsIK0Eme0cb4GeYqtADvrS3SYQaOgkccMdACvQpHxvbPowMhzr53g==
      - INFLUXDB-ORG=PG3
      - INFLUXDB-BUCKET=crawl-url
    networks:
      - app-to-db

networks:
  app-to-db:
  db-to-grafana:

