version: '3.3'

services:
  db:
    image: influxdb:2.0
    ports:
      - '8086:8086'
    volumes:
      - ./influxdbv2:/root/.influxdbv2
    networks:
      - app-to-db
      - db-to-grafana
    

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - './grafana:/var/lib/grafana'
    networks:
      - db-to-grafana
    depends_on:
      - db

  
  web:
    depends_on:
      - db
    restart: on-failure:10
    build: crawler
    volumes:
      - ./crawler/sources/:/sources
    environment:
      - "INFLUXDB-HOST=http://db:8086"
      - LIST=/sources/list.yml
      - INFLUXDB-TOKEN=HD0ahsAW5grFszjiwPQDV_BZbr8Idfto95lgvPKQUpSOn0KlQxYDMCsaHEeY2fhmi8G6W4LDA8LIorbkwH7YLg==
      - INFLUXDB-ORG=PG3
      - INFLUXDB-BUCKET=crawl-url
    networks:
      - app-to-db

networks:
  app-to-db:
  db-to-grafana:

